INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Trainee EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Solver' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor de Recursos Humanos EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor de Consultoria EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor de Projetos Especiais EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor Administrativo EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor de Marketing EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor Presidente EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Ex-Membro EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor Financeiro EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Conselheiro EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Trainee não efetivado' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Free Lancer EJ' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Aluno FGV' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Sócio(a)' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente de Marketing' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a) Comercial' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a) de RH' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a)' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente Comercial' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Assessor de Imprensa' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Futuro proprietário' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a)  Adjunto(a)' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Patologista' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista de Procesos' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente de Mercado' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Superintendente Geral' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Administrador' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Coordenadora' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Assistente' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Presidente' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Socio Proprietário' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Representante' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Coordenador Geral' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a) Adm/Financeiro' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Oficial' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Representante Comercial' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente de Vendas' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Desenvolvedor de novos negócios' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente de Administração' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Proprietário(a)' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a) Técnico(a)' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Diretor(a) Executiva' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Secretária' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Editora' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Vice-presidente' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Marido/Mulher do(a) Proprietário(a)' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Assistente da Gerencia' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Sócio(a) Gerente' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Filho do Proprietário' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Proprietário Potencial' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Consultora de RH' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Brand manager' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Engenheiro Serviços Adm.' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente Geral' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Ger. Pesquisa de Mercado' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Agente Administrativo' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Agente Manutenção' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista Recursos Humanos' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista de Sistemas Jr' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista de Sistema Pleno' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista de Sistemas Sênior' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista Supervisor de Usuário' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Assistente Administrativo' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Assistente Social' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Administrativo' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Audiovisual' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Bibliotécnico' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar de Editoria Eletronica' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Enf Trabalho' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Manutenção' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Portaria' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Auxiliar Técnico' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Bedel' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Bibliotécnico' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Comprador SR' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Contínuo' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Copeira' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Eletricista' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente Bibliotécnico' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente CACR' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente DAD' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente DFC' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente DMP' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente DRH' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Gerente DVI' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Motorista' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Operador Máquina Copiadora' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Produtor de Arte' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Programador' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Recepcionista' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Revisor Texto' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Secretária Diretoria' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Secretária Ensino' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Superintendente Administrativo' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Superintendente Apoio Acadêmico' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Administrativo' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Contabilidade' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Desenvolvimento Sistema' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Estágio e Colocação' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Livraria' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor RAE' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Rec Humanos' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Secretaria' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor SEF' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Supervisor Suporte Usuário' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Manutenção Predial' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Audiovisual' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Contabil' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Edit Eletronica' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Secretária Júnior' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Secretária Pleno' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Secretária Sênior' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Sup Usuário' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Técnico Sup Usuário Jr' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Telefonista' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Vendedor' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Zelador' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Analista Econômico' );
INSERT INTO cargo_ext ( cex_nome ) VALUES ( 'Trainee' );
