INSERT INTO setor ( set_nome ) VALUES ( 'Administração, Economia e Ciências Contábeis' );
INSERT INTO setor ( set_nome ) VALUES ( 'Propaganda e Marketing' );
INSERT INTO setor ( set_nome ) VALUES ( 'Informática' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia Civil' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia Agrônoma' );
INSERT INTO setor ( set_nome ) VALUES ( 'Arquitetura e Urbanismo' );
INSERT INTO setor ( set_nome ) VALUES ( 'Matemática e Estatística' );
INSERT INTO setor ( set_nome ) VALUES ( 'Farmácia' );
INSERT INTO setor ( set_nome ) VALUES ( 'Hotelaria' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia Química' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia Eletro-Eletrônica' );
INSERT INTO setor ( set_nome ) VALUES ( 'Direito' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia' );
INSERT INTO setor ( set_nome ) VALUES ( 'Zootecnia' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia de Produção e Mecúnica' );
INSERT INTO setor ( set_nome ) VALUES ( 'Federação' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia de Alimentos' );
INSERT INTO setor ( set_nome ) VALUES ( 'Geologia' );
INSERT INTO setor ( set_nome ) VALUES ( 'Engenharia Aeronáutica' );
INSERT INTO setor ( set_nome ) VALUES ( 'Análise de Sistemas' );
