INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Tributária' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Estratégia' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Planejamento Estratégico' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Logística' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Reestruturação' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Sistemas e Métodos' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Diagnóstico' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Estruturação' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Qualidade' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Controle' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Análise Organizacional' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Pesquisa de Mercado' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Viabilidade Mercadológica' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Planejamento de Marketing' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Estratégia de Comunicação' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Custos' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Análise Financeira' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Fluxo de Caixa' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Crédito' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Treinamentos' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Política de RH' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Cargos e Salários' );
INSERT INTO tipo_projeto ( tpj_nome ) VALUES ( 'Viabilidade' );
